on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.0, 7.1, 7.2, 7.3, 7.4, 8.0, 8.1]
    services:
      redis:
        image: redis
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: sudo apt-get install pkg-config libzstd1-dev liblz4-dev

      - name: Configure and build
        run: |
          phpize
          ./configure --enable-redis-lzf --enable-redis-zstd --enable-redis-lz4 --with-liblz4
          sudo make install

      - name: Run tests
        run: |
          php tests/TestRedis.php --class Redis --user phpredis --auth phpredis
          php tests/TestRedis.php --class RedisArray --user phpredis --auth phpredis
          php tests/TestRedis.php --class RedisCluster --user phpredis --auth phpredis
          php tests/TestRedis.php --class RedisSentinel --auth phpredis
